# Generated by Django 2.2.10 on 2020-03-24 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cheatingdash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDERID', models.CharField(max_length=300, verbose_name='ORDER ID')),
                ('TXNDATE', models.DateTimeField(auto_now_add=True, verbose_name='TXN DATE')),
                ('TXNID', models.CharField(blank=True, max_length=300, null=True, verbose_name='TXN ID')),
                ('TXNTYPE', models.CharField(blank=True, max_length=300, null=True, verbose_name='TXNTYPE')),
                ('BANKTXNID', models.CharField(blank=True, max_length=300, null=True, verbose_name='BANK TXN ID')),
                ('BANKNAME', models.CharField(blank=True, max_length=50, null=True, verbose_name='BANK NAME')),
                ('RESPCODE', models.IntegerField(verbose_name='RESP CODE')),
                ('PAYMENTMODE', models.CharField(blank=True, max_length=10, null=True, verbose_name='PAYMENT MODE')),
                ('GATEWAYNAME', models.CharField(blank=True, max_length=30, null=True, verbose_name='GATEWAY NAME')),
                ('MID', models.CharField(blank=True, max_length=100, null=True)),
                ('RESPMSG', models.TextField(max_length=250, verbose_name='RESP MSG')),
                ('TXNAMOUNT', models.FloatField(max_length=250, verbose_name='TXN AMOUNT')),
                ('REFUNDAMT', models.FloatField(max_length=250, verbose_name='REFUNDAMT')),
                ('STATUS', models.CharField(max_length=12, verbose_name='STATUS')),
            ],
        ),
        migrations.CreateModel(
            name='PaytmHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDERID', models.CharField(max_length=300, verbose_name='ORDER ID')),
                ('TXNDATE', models.DateTimeField(auto_now_add=True, verbose_name='TXN DATE')),
                ('TXNID', models.CharField(blank=True, max_length=300, null=True, verbose_name='TXN ID')),
                ('BANKTXNID', models.CharField(blank=True, max_length=300, null=True, verbose_name='BANK TXN ID')),
                ('BANKNAME', models.CharField(blank=True, max_length=50, null=True, verbose_name='BANK NAME')),
                ('RESPCODE', models.IntegerField(verbose_name='RESP CODE')),
                ('PAYMENTMODE', models.CharField(blank=True, max_length=10, null=True, verbose_name='PAYMENT MODE')),
                ('CURRENCY', models.CharField(blank=True, max_length=4, null=True, verbose_name='CURRENCY')),
                ('GATEWAYNAME', models.CharField(blank=True, max_length=30, null=True, verbose_name='GATEWAY NAME')),
                ('MID', models.CharField(blank=True, max_length=100, null=True)),
                ('RESPMSG', models.TextField(max_length=250, verbose_name='RESP MSG')),
                ('TXNAMOUNT', models.FloatField(max_length=250, verbose_name='TXN AMOUNT')),
                ('STATUS', models.CharField(max_length=12, verbose_name='STATUS')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_payment_paytm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
