# Generated by Django 2.2.10 on 2020-03-28 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cheatingdash', '0004_auto_20200327_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='userSubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubsplanName', models.CharField(blank=True, max_length=4, null=True)),
                ('durationMonth', models.IntegerField()),
                ('price', models.IntegerField()),
                ('BoostCount', models.IntegerField()),
                ('BoostMinute', models.IntegerField()),
                ('SuperLikeCount', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
