# Generated by Django 2.2.10 on 2020-04-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheatingdash', '0007_userprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
