# Generated by Django 2.2.10 on 2020-04-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheatingdash', '0008_auto_20200416_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchid', models.IntegerField()),
                ('user1id', models.IntegerField()),
                ('user2id', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
