# Generated by Django 2.2.10 on 2020-04-17 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cheatingdash', '0009_matchprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptions',
            name='subsdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
