# Generated by Django 2.2 on 2020-04-17 13:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anonymous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(blank=True, max_length=12, null=True)),
                ('country_code', models.CharField(blank=True, max_length=4, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('auth_token', models.CharField(max_length=100)),
                ('app_version', models.FloatField()),
                ('device_id', models.CharField(max_length=30)),
                ('device_type', models.CharField(max_length=10, null=True)),
                ('fcm_token', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashback_percentage', models.DecimalField(decimal_places=2, max_digits=6, max_length=10)),
                ('referral_amount', models.DecimalField(decimal_places=2, max_digits=6, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Height',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(blank=True, max_length=20, verbose_name='Height in Cm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=30)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PushNotificationMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.IntegerField(blank=True, choices=[(1, 'hi'), (2, 'like'), (3, 'superlike'), (4, 'heart'), (5, 'match'), (6, 'referral')])),
                ('msg_title', models.CharField(blank=True, max_length=60)),
                ('msg_body', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_no', models.CharField(blank=True, max_length=15)),
                ('country_code', models.CharField(blank=True, max_length=4, null=True)),
                ('dob', models.DateField(blank=True)),
                ('gender', models.CharField(blank=True, max_length=6)),
                ('body_type', models.CharField(blank=True, max_length=10)),
                ('about_me', models.CharField(blank=True, max_length=100)),
                ('user_type', models.CharField(blank=True, max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=30)),
                ('height', models.CharField(blank=True, max_length=20)),
                ('weight', models.CharField(blank=True, max_length=10)),
                ('latitude', models.FloatField(blank=True, default=0.0)),
                ('longitude', models.FloatField(blank=True, default=0.0)),
                ('distance', models.FloatField(default=0.0)),
                ('referral_code', models.CharField(max_length=10)),
                ('priority', models.IntegerField(blank=True, default=0)),
                ('profile_verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('app_version', models.FloatField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=30, null=True)),
                ('device_type', models.CharField(blank=True, max_length=10, null=True)),
                ('fcm_token', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_complete_percentage', models.IntegerField(blank=True, default=0)),
                ('profile_update_percentage', models.IntegerField(default=0)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(blank=True, max_length=20, verbose_name='Weight in Kg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsersNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, max_length=200, null=True)),
                ('action', models.CharField(blank=True, max_length=200, null=True)),
                ('msg_title', models.CharField(blank=True, max_length=200, null=True)),
                ('msg_body', models.CharField(blank=True, max_length=200, null=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('friend_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='userprofile.Users')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='userprofile.Users')),
            ],
        ),
        migrations.CreateModel(
            name='UserprofileVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilevideos', models.ImageField(upload_to='profiles_vedios')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profilevideos', to='userprofile.Users')),
            ],
        ),
        migrations.CreateModel(
            name='UserprofileImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepics', models.ImageField(upload_to='profiles')),
                ('is_profile', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profilepics', to='userprofile.Users')),
            ],
        ),
        migrations.CreateModel(
            name='UserPrivacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.BooleanField(default=False)),
                ('showme', models.BooleanField(default=False)),
                ('aboutme', models.BooleanField(default=False)),
                ('sharephotos', models.BooleanField(default=False)),
                ('occupation', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Users')),
            ],
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=100)),
                ('session_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Users')),
            ],
        ),
        migrations.CreateModel(
            name='SuperLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superlike_count', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('superliked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superliked', to='userprofile.Users')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superlike_by', to='userprofile.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=256)),
                ('report_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported', to='userprofile.Users')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to='userprofile.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age_from', models.IntegerField(blank=True, null=True)),
                ('age_to', models.IntegerField(blank=True, null=True)),
                ('distance_min', models.CharField(blank=True, max_length=10, null=True)),
                ('distance_max', models.CharField(blank=True, max_length=10, null=True)),
                ('distance_no_limit', models.BooleanField(default=False)),
                ('preferences_update_percentage', models.IntegerField(default=0)),
                ('age_no_limit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Users')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
                ('otp_expire_at', models.DateTimeField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Anonymous')),
            ],
        ),
        migrations.CreateModel(
            name='Nopes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('nope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nope', to='userprofile.Users')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='userprofile.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matches', models.ManyToManyField(blank=True, related_name='matches', to='userprofile.Users')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_by', to='userprofile.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='userprofile.Users')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='userprofile.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Hi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hi_count', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hi_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hi_to', to='userprofile.Users')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hi_by', to='userprofile.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Heart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_count', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heart_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heart_to', to='userprofile.Users')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heaet_by', to='userprofile.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked', to='userprofile.Users')),
                ('blocked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='userprofile.Users')),
            ],
        ),
    ]
