# Generated by Django 2.2 on 2020-04-17 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('accessories_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaytmPaymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30, unique=True)),
                ('txn_id', models.CharField(max_length=100)),
                ('txn_type', models.CharField(blank=True, max_length=30)),
                ('bank_txn_id', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=50)),
                ('resp_code', models.IntegerField()),
                ('payment_mode', models.CharField(blank=True, max_length=10)),
                ('gatway_name', models.CharField(blank=True, max_length=30)),
                ('mid', models.CharField(blank=True, max_length=100)),
                ('resp_msg', models.TextField(max_length=250)),
                ('txn_amount', models.DecimalField(decimal_places=2, max_digits=6, max_length=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=6, max_length=10)),
                ('status', models.CharField(max_length=12)),
                ('txn_date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Plan Price')),
                ('validity', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('hi', models.IntegerField(default=0, verbose_name='Number of Hi')),
                ('hearts', models.IntegerField(default=0, verbose_name='Number of Hearts')),
                ('likes', models.IntegerField(default=0, verbose_name='Number of Likes')),
                ('boosts', models.IntegerField(default=0, verbose_name='Number of Boosts')),
                ('talktime', models.IntegerField(default=0, verbose_name='Talk Time Minutes')),
                ('superlikes', models.IntegerField(default=0, verbose_name='Number of Super Like')),
                ('wallet_percentage', models.FloatField(default=0.0)),
                ('discount_percentage', models.FloatField(default=0.0)),
                ('video_enabled', models.BooleanField(default=False)),
                ('audio_enabled', models.BooleanField(default=False)),
                ('sees_control', models.BooleanField(default=False)),
                ('interested_profile', models.BooleanField(default=False)),
                ('hide_ads', models.BooleanField(default=False)),
                ('profile_control', models.BooleanField(default=False)),
                ('stickers', models.BooleanField(default=False)),
                ('scrach_enable', models.BooleanField(default=False)),
                ('e_greetings_enable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_amount', models.DecimalField(decimal_places=2, default=1000, max_digits=6)),
                ('referral_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Users')),
            ],
        ),
        migrations.CreateModel(
            name='UserDailyDose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='Basic', max_length=50, null=True)),
                ('remaining_hi', models.IntegerField(default=5)),
                ('remaining_likes', models.IntegerField(default=100)),
                ('remaining_hearts', models.IntegerField(default=5)),
                ('remaining_boosts', models.IntegerField(default=5)),
                ('remaining_talktime', models.IntegerField(default=5)),
                ('remaining_superlikes', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('plan_expire_at', models.DateTimeField(blank=True, null=True)),
                ('payment_token', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.PlanDetails')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Users')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(blank=True, max_length=10, null=True)),
                ('plan_name', models.CharField(blank=True, max_length=30, null=True)),
                ('accessories_id', models.CharField(blank=True, max_length=10, null=True)),
                ('accessories_name', models.CharField(blank=True, max_length=30, null=True)),
                ('order_id', models.CharField(max_length=30, unique=True)),
                ('paytm_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('cashback_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('wallet_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('plan_price_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('plan_request_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Users')),
            ],
        ),
        migrations.CreateModel(
            name='PlanPurchedByUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(blank=True, max_length=10, null=True)),
                ('plan_name', models.CharField(blank=True, max_length=30, null=True)),
                ('accessories_id', models.CharField(blank=True, max_length=10, null=True)),
                ('accessories_name', models.CharField(blank=True, max_length=30, null=True)),
                ('paytm_txn_id', models.CharField(blank=True, max_length=40, null=True)),
                ('order_id', models.CharField(max_length=30, unique=True)),
                ('paytm_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('cashback_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('wallet_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('plan_price_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('plan_purched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Users')),
            ],
        ),
        migrations.AddField(
            model_name='plandetails',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plandetail', to='subscription.Plans'),
        ),
        migrations.CreateModel(
            name='AccessoriesDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Accessories Price')),
                ('validity', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('remaining_hi', models.IntegerField(default=0, verbose_name='Number of Hi')),
                ('remaining_hearts', models.IntegerField(default=0, verbose_name='Number of Hearts')),
                ('remaining_boosts', models.IntegerField(default=0, verbose_name='Number of Boosts')),
                ('remaining_talktime', models.IntegerField(default=0, verbose_name='Number of Talk Time')),
                ('remaining_superlikes', models.IntegerField(default=0, verbose_name='Number of Super Like')),
                ('wallet_percentage', models.FloatField(default=0.0)),
                ('discount_percentage', models.FloatField(default=0.0)),
                ('accessories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.Accessories')),
            ],
        ),
    ]
